@call package.bat toolkit-dnf
@call package.bat toolkit-pfs
@call package.bat toolkit-pkg
@call package.bat toolkit-renpy
@call package.bat toolkit-qqfo
@call package.bat toolkit-qqhx
@call package.bat toolkit-qqt
@call package.bat toolkit-shikari
@call package.bat toolkit-viewer
